version: '2'

services:
  attacker:
    build: ../ubuntu-ddos
    volumes:
    - ../volumes/log:/log
    - ../volumes/config:/bonesi-master/config
    links:
    - target
    tty: true
    stdin_open: true

  scanner:
    build: ../ubuntu-port-scanner
    volumes:
    - ../volumes/log:/log
    - ../volumes/config:/config
    links:
    - target
    tty: true
    stdin_open: true

  pinger:
    build: ../ubuntu-pinger
    volumes:
    - ../volumes/node/target:/opt/node
    links:
    - target
    ports:
    - "8080:8080"

  target:
    build: ../ubuntu-target
    volumes:
    - ../volumes/log:/log
    - ../volumes/node/target:/opt/node
    ports:
    - "8888:8888"

