version: '2'

services:
  attacker:
    build: ./../ubuntu-ddos
    networks:
      app_net:
        ipv4_address: 172.10.0.2
    depends_on:
    - probe
  scanner:
    build: ./../ubuntu-port-scanner
    networks:
      app_net:
        ipv4_address: 172.10.0.3
    depends_on:
    - probe
  probe:
    build: ./../ubuntu-probe
    networks:
      app_net:
        ipv4_address: 172.10.0.4
    ports:
    - "8888:8888"

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.10.0.0/16
        gateway: 172.10.0.1

