version: '2'

services:
  attacker:
    build: ../ubuntu-ddos
    container_name: attacker
    volumes:
    - log:/log
    - attacker-config:/bonesi-master/config
    links:
    - target
    tty: true
    stdin_open: true

  scanner:
    build: ../ubuntu-port-scanner
    container_name: scanner
    volumes:
    - log:/usr/local/sbin/log
    - scanner-config:/usr/local/sbin/config
    links:
    - target
    tty: true
    stdin_open: true

# using container_name and/or exposed ports connected to specific host ports will prevent pinger from being scalable
  pinger:
    build: ../ubuntu-pinger
    #container_name: pinger
    volumes:
    - log:/log
    - pinger-node:/opt/node
    links:
    - target
    ports:
    - "8866"

  target:
    build: ../ubuntu-target
    container_name: target
    volumes:
    - log:/log
    - target-node:/opt/node
    ports:
    - "8888:8888"

  analyser:
    build: ../ubuntu-anaconda-scapy
    container_name: analyser
    volumes:
    - log:/usr/local/sbin/log
    - analyser-config:/usr/local/sbin/config

volumes:
  log:
  pinger-node:
  target-node:
  analyser-config:
  attacker-config:
  scanner-config:
