version: '2'

services:
  attacker:
    build: ../ubuntu-ddos
    container_name: attacker
    volumes:
    - ./log:/log
    - ./config:/bonesi-master/config
    links:
    - target
    tty: true
    stdin_open: true

  scanner:
    build: ../ubuntu-port-scanner
    container_name: scanner
    volumes:
    - ./log:/log
    - ./config:/config
    links:
    - target
    tty: true
    stdin_open: true

# using container_name and/or exposed ports will prevent pinger from being scalable
  pinger:
    build: ../ubuntu-pinger
#    container_name: pinger
    volumes:
    - ./node-pinger:/opt/node
    links:
    - target
#    ports:
#    - "8080:8080"

  target:
    build: ../ubuntu-target
    container_name: target
    volumes:
    - ./log:/log
    - ./node-target:/opt/node
    ports:
    - "8888:8888"

