version: '2'

services:
  commander:
    build: ../alpine-commander
    container_name: commander
    volumes:
    - log:/log
    tty: true

  attacker:
    build: ../ubuntu-ddos
    container_name: attacker
    volumes:
    - log:/log
    - attacker-config:/bonesi-master/config
    links:
    - target
    tty: true

  scanner:
    build: ../ubuntu-port-scanner
    container_name: scanner
    volumes:
    - log:/usr/local/sbin/log
    - scanner-config:/usr/local/sbin/config
    links:
    - target
    tty: true

# using container_name and/or exposed ports connected to specific host ports will prevent pinger from being scalable
  pinger:
    build: ../ubuntu-pinger
    #container_name: pinger
    volumes:
    - log:/log
    - pinger-node:/opt/node
    links:
    - target
    ports:
    # port 8866 will be exposed by container and assigned to a random port on the host machine
    - "8866"

# using container_name and/or exposed ports connected to specific host ports will prevent target from being scalable
  target:
    build: ../ubuntu-target
    container_name: target
    volumes:
    - log:/log
    - target-node:/opt/node
    ports:
    - "8888:8888"

  analyser:
    build: ../ubuntu-anaconda-scapy
    container_name: analyser
    volumes:
    - log:/usr/local/sbin/log
    - data:/usr/local/sbin/data
    - analysis:/usr/local/sbin/analysis
    - analyser-config:/usr/local/sbin/config
    tty: true
    stdin_open: true

volumes:
  log:
  data:
  analysis:
  pinger-node:
  target-node:
  analyser-config:
  attacker-config:
  scanner-config:
