version: 1
formatters:
  threaded:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(processName)s - %(threadName)s - %(message)s'
filters:
  pcap_filter:
    name: pcap_to_csv
  graph_filter:
    name: csv_to_graph
handlers:
  console_err:
    class: logging.StreamHandler
    level: WARN
    formatter: threaded
    stream: ext://sys.stderr
  pcap_file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: threaded
    filename: log/pcap_to_csv.log
    backupCount: 10
    maxBytes: 10485760
    filters: [pcap_filter]
  graph_file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: threaded
    filename: log/csv_to_graph.log
    backupCount: 10
    maxBytes: 10485760
    filters: [graph_filter]
loggers:
  pcap_to_csv:
    handlers: [pcap_file]
    propagate: no
  csv_to_graph:
    handlers: [graph_file]
    propagate: no
root:
  level: DEBUG
  handlers: [console_err]
