version: 1
formatters:
  detailed:
    format: '%(asctime)s - (%(levelname)s) - %(name)s - %(process)d/%(thread)d - %(filename)s#%(module)s#%(funcName)s/%(lineno)d - %(message)s'
filters:
  pcap_filter:
    name: pcap_to_csv
  graph_filter:
    name: csv_to_graph
  port_scanner_filter:
    name: port_scanner
handlers:
  console_err:
    class: logging.StreamHandler
    level: WARN
    formatter: detailed
    stream: ext://sys.stderr
  pcap_file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: detailed
    filename: log/pcap_to_csv.log
    backupCount: 10
    maxBytes: 10485760
    filters: [pcap_filter]
  graph_file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: detailed
    filename: log/csv_to_graph.log
    backupCount: 10
    maxBytes: 10485760
    filters: [graph_filter]
  port_scanner_file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: log/port_scanner.log
    backupCount: 10
    maxBytes: 10485760
    filters: [port_scanner_filter]
loggers:
  pcap_to_csv:
    handlers: [pcap_file]
    propagate: no
  csv_to_graph:
    handlers: [graph_file]
    propagate: no
  port_scanner:
    handlers: [port_scanner_file]
    propagate: no
root:
  level: DEBUG
  handlers: [console_err]
