version: 1
formatters:
  detailed:
    format: '%(asctime)s - (%(levelname)s) - %(name)s - %(process)d/%(thread)d - %(filename)s#%(module)s#%(funcName)s/%(lineno)d - %(message)s'
filters:
  port_scanner_filter:
    name: port_scanner
handlers:
  console_err:
    class: logging.StreamHandler
    level: WARN
    formatter: detailed
    stream: ext://sys.stderr
  port_scanner_file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: log/port_scanner.log
    backupCount: 10
    maxBytes: 10485760
    filters: [port_scanner_filter]
loggers:
  port_scanner:
    handlers: [port_scanner_file]
    propagate: no
root:
  level: DEBUG
  handlers: [console_err]
